In [19]:
import tensorflow as tf 
import os
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [20]:
mixed_data_100_5079_replace = pd.read_csv('E:/hxf prediction/data_mimic/hxf/notes_extract/total_code/mixed_data_0717_drop_replace_fill_100_5079.csv')
mixed_data_100_5079_replace.shape

(5199, 309)

In [21]:
mixed_data_100_5079_replace = mixed_data_100_5079_replace.drop(labels=['Unnamed: 0'], axis=1)
mixed_data_100_5079_replace

1         2         3         4         5       6_x         7  \
0    -0.007089  0.004145  0.038405 -0.052687 -0.049249  0.070052 -0.030874   
1    -0.046269 -0.017732  0.040526 -0.074210 -0.037897  0.060724 -0.016219   
2    -0.048322 -0.043990  0.016089 -0.098154 -0.019360  0.066105 -0.010958   
3    -0.008100 -0.033179  0.025611 -0.066074 -0.032589  0.076273 -0.043867   
4    -0.082258 -0.013484  0.004785 -0.071620 -0.047045  0.049379  0.002257   
...        ...       ...       ...       ...       ...       ...       ...   
5194 -0.021533 -0.024169  0.038631 -0.054892 -0.038952  0.077706 -0.036869   
5195 -0.038366  0.003058  0.030392 -0.053761 -0.034978  0.068232 -0.028096   
5196 -0.015536 -0.042503  0.009408 -0.054958 -0.025101  0.075214 -0.017778   
5197 -0.097241  0.007172  0.017310 -0.056375 -0.059922  0.028442  0.012607   
5198 -0.029792 -0.024298  0.029648 -0.059690 -0.031142  0.057555 -0.009290   

             8         9        10  ...     50963  50909  50903  50904  50905  \
0     0.028542  0.068825  0.091948  ...  10558.00   34.3   4.04  43.74   89.0   
1     0.055877  0.110071  0.088731  ...  15219.75   34.3   4.04  43.74   89.0   
2     0.058539  0.120996  0.113395  ...  15219.75   34.3   4.04  43.74   89.0   
3     0.045307  0.068330  0.083049  ...  15219.75   34.3   4.04  43.74   89.0   
4     0.059376  0.113682  0.106364  ...  15219.75   34.3   4.04  43.74   89.0   
...        ...       ...       ...  ...       ...    ...    ...    ...    ...   
5194  0.039681  0.081134  0.065088  ...  15219.75   34.3   4.04  43.74   89.0   
5195  0.049303  0.105394  0.074794  ...  15219.75   34.3   2.80  66.00  102.0   
5196  0.059893  0.092698  0.055450  ...  15219.75   34.3   4.04  43.74   89.0   
5197  0.055554  0.116205  0.118019  ...  15219.75   34.3   4.04  43.74   89.0   
5198  0.045681  0.106409  0.078930  ...  15219.75   34.3   4.04  43.74   89.0   

       50907   51000  50906   age  flag  
0     158.92  139.06  99.16  85.0   1.0  
1     158.92  139.06  99.16  67.0   0.0  
2     158.92  139.06  99.16  67.0   0.0  
3     174.00  139.06  99.16  84.0   1.0  
4     158.92  139.06  99.16  58.0   0.0  
...      ...     ...    ...   ...   ...  
5194  158.92  139.06  99.16  75.0   1.0  
5195  188.00  101.00  99.16  69.0   1.0  
5196  158.92  139.06  99.16  89.0   1.0  
5197  158.92  139.06  99.16  86.0   0.0  
5198  158.92  139.06  99.16  86.0   0.0  

[5199 rows x 308 columns]

In [22]:
#corr_data = data.corr()['expire_flag'].sort_values(ascending = False)

In [23]:
#in_corr_data = data[corr_data[(corr_data > 0.1) | (corr_data > -0.1)].index]

In [24]:
X, y = np.array(mixed_data_100_5079_replace.drop(labels=['flag'], axis=1)), np.array(mixed_data_100_5079_replace['flag'].apply(int))

In [25]:
X.shape

(5199, 307)

In [26]:
y

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666,test_size = 0.33 )

In [28]:
X_train_vec, X_train_need_scale = X_train[:, 0:200], X_train[:, 200:]
X_train_need_scale

array([[  1.  ,   1.  ,   2.  , ..., 139.06,  99.16,  61.  ],
       [  4.  ,   5.  ,   3.  , ..., 139.06,  99.16,  87.  ],
       [  1.  ,   0.  ,   2.  , ..., 139.06,  99.16,  46.  ],
       ...,
       [  0.  ,   3.  ,   0.  , ..., 112.  ,  99.16,  88.  ],
       [  1.  ,   1.  ,   0.  , ..., 139.06,  99.16,  56.  ],
       [  3.  ,   1.  ,   0.  , ...,  69.  ,  99.16,  74.  ]])

In [29]:
X_train_vec

array([[-0.0616547 , -0.00719389,  0.02209863, ...,  0.04419197,
         0.04840468,  0.1125212 ],
       [-0.04367821, -0.00468176,  0.01873666, ...,  0.06050809,
         0.07758447,  0.08507637],
       [-0.01103216, -0.023751  ,  0.02704758, ...,  0.04251143,
         0.04903732,  0.10087774],
       ...,
       [-0.0687694 ,  0.00432208,  0.03931623, ...,  0.05896778,
         0.05197511,  0.127062  ],
       [-0.10637879, -0.0293281 ,  0.0025199 , ...,  0.04118515,
         0.07000919,  0.10419425],
       [-0.0150273 ,  0.01286628,  0.01903607, ...,  0.06682524,
         0.04598877,  0.11499347]])

In [30]:
X_train_vec.shape

(3483, 200)

In [31]:
X_train_need_scale.shape

(3483, 107)

In [32]:
X_test_vec, X_test_need_scale = X_test[:, 0:200], X_test[:, 200:]
X_test_need_scale

array([[  3.  ,   3.  ,   0.  , ..., 139.06,  99.16,  62.  ],
       [  0.  ,   2.  ,   0.  , ..., 109.  ,  99.16,  83.  ],
       [  1.  ,   0.  ,   0.  , ..., 139.06,  99.16,  75.  ],
       ...,
       [  4.  ,  10.  ,   1.  , ..., 139.06,  99.16,  84.  ],
       [  1.  ,   4.  ,   2.  , ..., 139.06,  99.16,  68.  ],
       [  0.  ,   0.  ,   0.  , ..., 139.06,  99.16,  69.  ]])

In [33]:
X_test_vec

array([[-0.0150447 , -0.01556175,  0.02948797, ...,  0.0314746 ,
         0.0437981 ,  0.08663017],
       [-0.04189379, -0.00865391,  0.03074749, ...,  0.04190846,
         0.05817086,  0.1084365 ],
       [-0.06006065, -0.00641395, -0.00533319, ...,  0.02041156,
         0.04046414,  0.1378125 ],
       ...,
       [-0.03235763, -0.01355557,  0.02959701, ...,  0.0397548 ,
         0.06472966,  0.10936951],
       [-0.04433653, -0.026616  ,  0.01592735, ...,  0.04744394,
         0.05462258,  0.10160053],
       [-0.0436074 , -0.00051947,  0.03306991, ...,  0.05579429,
         0.04935778,  0.12380271]])

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [35]:
standard_scaler = StandardScaler()
standard_scaler.fit(X_train_need_scale)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [36]:
standard_scaler.mean_

array([1.92276773e+00, 1.77031295e+00, 9.43152455e-01, 8.25150732e-01,
       3.29413724e+02, 3.93051967e-01, 3.06643698e+01, 2.63313236e-01,
       6.49038185e-02, 5.63928682e+01, 1.22400287e+02, 3.14450359e+01,
       1.95047947e+01, 6.11076947e+01, 1.14967557e+01, 1.54853959e+02,
       4.31105627e+01, 1.38360034e+02, 1.17209483e+02, 8.39076946e+00,
       5.73153747e+01, 6.02228309e+01, 1.92120385e+01, 1.06151220e+01,
       1.01652024e+00, 3.11024235e+01, 1.36713178e+00, 1.04946196e+02,
       1.57793982e+02, 3.72003279e+03, 1.38028814e+02, 1.15352719e+02,
       7.98115705e+01, 5.10340798e+00, 1.15746942e+02, 4.16648866e+00,
       1.49531036e+01, 1.38579437e+02, 1.45464278e+02, 1.22751163e+01,
       1.29007034e+01, 2.73993115e+00, 2.94938530e+01, 5.61876543e+01,
       5.80802756e+01, 1.09907936e+02, 1.75101924e-01, 5.56662590e+01,
       1.36375263e+02, 1.35886882e+02, 1.44291631e+02, 2.90510393e+01,
       2.01042205e+00, 2.18291398e+02, 8.34460237e+00, 2.40643239e+01,
      

In [37]:
X_train_standard = standard_scaler.transform(X_train_need_scale)
X_test_standard = standard_scaler.transform(X_test_need_scale)

In [38]:
X_train_standard.shape

(3483, 107)

In [39]:
X_test_standard.shape

(1716, 107)

In [40]:
X_train_standard = np.hstack((X_train_vec, X_train_standard))
X_test_standard = np.hstack((X_test_vec, X_test_standard))

In [41]:
print(X_train_standard.shape)
print(X_test_standard.shape)

(3483, 307)
(1716, 307)


In [42]:
# def load_data(filename):
#     """read data from data file."""
#     with open(filename, 'rb') as f:
#         data = pickle.load(f, encoding='bytes')
#         return data[b'data'], data[b'labels']

# tensorflow.Dataset.
class DiseaseData:
    def __init__(self, train_model=True, need_shuffle=True):
        if train_model:
            self._data = X_train_standard
            self._labels = y_train
        else:
            self._data = X_test_standard
            self._labels = y_test
        print(self._data.shape)
#         print(self._data.dtype)
        print(self._labels.shape)
#         print(self._labels.dtype)

        self._num_examples = self._data.shape[0]
        self._need_shuffle = need_shuffle
        self._indicator = 0
        if self._need_shuffle:
            self._shuffle_data()
            
    def _shuffle_data(self):
        # [0,1,2,3,4,5] -> [5,3,2,4,0,1]
        p = np.random.permutation(self._num_examples)
        self._data = self._data[p]
        self._labels = self._labels[p]
    
    def next_batch(self, batch_size):
        """return batch_size examples as a batch."""
        end_indicator = self._indicator + batch_size
        if end_indicator > self._num_examples:
            if self._need_shuffle:
                self._shuffle_data()
                self._indicator = 0
                end_indicator = batch_size
            else:
                raise Exception("have no more examples")
        if end_indicator > self._num_examples:
            raise Exception("batch size is larger than all examples")
        batch_data = self._data[self._indicator: end_indicator]
        batch_labels = self._labels[self._indicator: end_indicator]
        self._indicator = end_indicator
        return batch_data, batch_labels

train_data = DiseaseData(True, True)
test_data = DiseaseData(False, False)
# test_data.next_batch(20)

(3483, 307)
(3483,)
(1716, 307)
(1716,)


In [ ]:
# x = tf.placeholder(tf.float32, [None, 94])
# # [None], eg: [0,5,6,3]
# y = tf.placeholder(tf.int64, [None])
# hidden1 = tf.layers.dense(x, 100, activation=tf.nn.relu)
# hidden2 = tf.layers.dense(hidden1, 100, activation=tf.nn.relu)
# hidden3 = tf.layers.dense(hidden2, 50, activation=tf.nn.relu)
# y_ = tf.layers.dense(hidden3, 1)


# # loss = tf.losses.sparse_softmax_cross_entropy(labels=y, logits=y_)
# # y_ -> sofmax
# # y -> one_hot
# # loss = ylogy_

# # indices
# # [None, 1]
# p_y_1 = tf.nn.sigmoid(y_)
# # [None, 1]
# y_reshaped = tf.reshape(y, (-1, 1))
# y_reshaped_float = tf.cast(y_reshaped, tf.float32)
# loss = tf.reduce_mean(tf.square(y_reshaped_float - p_y_1))

# # bool
# predict = p_y_1 > 0.5
# # [1,0,1,1,1,0,0,0]
# correct_prediction = tf.equal(tf.cast(predict, tf.int64), y_reshaped)
# accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float64))
# # [1,0,1,1,1,0,0,0]
# correct_prediction = tf.equal(tf.cast(predict, tf.int64), y_reshaped)
# accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float64))

# with tf.name_scope('train_op'):
#     train_op = tf.train.AdamOptimizer(1e-3).minimize(loss)

In [45]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
x = tf.placeholder(tf.float32, [None, X.shape[1]])
y = tf.placeholder(tf.int64, [None])
hidden1 = tf.layers.dense(x, 400, activation=tf.nn.tanh)
hidden2 = tf.layers.dense(hidden1, 400, activation=tf.nn.tanh)
y_ = tf.layers.dense(hidden2, 1)
p_y_1 = tf.nn.sigmoid(y_)
y_reshaped = tf.reshape(y, (-1, 1))
y_reshaped_float = tf.cast(y_reshaped, tf.float32)
loss = tf.reduce_mean(tf.square(y_reshaped_float - p_y_1))
predict = p_y_1 > 0.5
correct_prediction = tf.equal(tf.cast(predict, tf.int64), y_reshaped)
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float64))
with tf.name_scope('train_op'):
    train_op = tf.train.AdamOptimizer(1e-3).minimize(loss)

Instructions for updating:
Use keras.layers.Dense instead.
Instructions for updating:
Please use `layer.__call__` method instead.


In [43]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
x = tf.placeholder(tf.float32, [None, X.shape[1]])
# [None]
y = tf.placeholder(tf.int64, [None])

# (3072, 1)
w = tf.get_variable('w', [x.get_shape()[-1], 1],
                   initializer=tf.random_normal_initializer(0, 1))
# (1, )
b = tf.get_variable('b', [1],
                   initializer=tf.constant_initializer(0.0))

# [None, 3072] * [3072, 1] = [None, 1]
y_ = tf.matmul(x, w) + b

# [None, 1]
p_y_1 = tf.nn.sigmoid(y_)
# [None, 1]
y_reshaped = tf.reshape(y, (-1, 1))
y_reshaped_float = tf.cast(y_reshaped, tf.float32)
loss = tf.reduce_mean(tf.square(y_reshaped_float - p_y_1))

# bool
predict = p_y_1 > 0.5
# [1,0,1,1,1,0,0,0]
correct_prediction = tf.equal(tf.cast(predict, tf.int64), y_reshaped)
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float64))

with tf.name_scope('train_op'):
    train_op = tf.train.AdamOptimizer(1e-3).minimize(loss)

Instructions for updating:
non-resource variables are not supported in the long term


In [46]:
init = tf.global_variables_initializer()
batch_size = 10
train_steps = 1000000
test_steps = 70

# run 100k: 50.5%
with tf.Session() as sess:
    sess.run(init)
    for i in range(train_steps):
        batch_data, batch_labels = train_data.next_batch(batch_size)
        loss_val, acc_val, _ = sess.run(
            [loss, accuracy, train_op],
            feed_dict={
                x: batch_data,
                y: batch_labels})
        if (i+1) % 500 == 0:
            print('[Train] Step: %d, loss: %4.5f, acc: %4.5f'
                  % (i+1, loss_val, acc_val))
        if (i+1) % 5000 == 0:
            test_data = DiseaseData(False, False)
            all_test_acc_val = []
            for j in range(test_steps):
                test_batch_data, test_batch_labels \
                    = test_data.next_batch(batch_size)
                test_acc_val = sess.run(
                    [accuracy],
                    feed_dict = {
                        x: test_batch_data, 
                        y: test_batch_labels
                    })
                all_test_acc_val.append(test_acc_val)
            test_acc = np.mean(all_test_acc_val)
            print('[Test ] Step: %d, acc: %4.5f'
                  % (i+1, test_acc))

[Train] Step: 500, loss: 0.15806, acc: 0.80000
[Train] Step: 1000, loss: 0.08971, acc: 0.90000
[Train] Step: 1500, loss: 0.16747, acc: 0.70000
[Train] Step: 2000, loss: 0.09077, acc: 0.90000
[Train] Step: 2500, loss: 0.10297, acc: 0.80000
[Train] Step: 3000, loss: 0.30529, acc: 0.60000
[Train] Step: 3500, loss: 0.02460, acc: 1.00000
[Train] Step: 4000, loss: 0.00228, acc: 1.00000
[Train] Step: 4500, loss: 0.19504, acc: 0.80000
[Train] Step: 5000, loss: 0.09838, acc: 0.90000
(1716, 307)
(1716,)
[Test ] Step: 5000, acc: 0.79000
[Train] Step: 5500, loss: 0.00064, acc: 1.00000
[Train] Step: 6000, loss: 0.00232, acc: 1.00000
[Train] Step: 6500, loss: 0.00008, acc: 1.00000
[Train] Step: 7000, loss: 0.00012, acc: 1.00000
[Train] Step: 7500, loss: 0.03517, acc: 0.90000
[Train] Step: 8000, loss: 0.00114, acc: 1.00000
[Train] Step: 8500, loss: 0.00001, acc: 1.00000
[Train] Step: 9000, loss: 0.00007, acc: 1.00000
[Train] Step: 9500, loss: 0.00011, acc: 1.00000
[Train] Step: 10000, loss: 0.00004, 

[Train] Step: 76500, loss: 0.00000, acc: 1.00000
[Train] Step: 77000, loss: 0.00000, acc: 1.00000
[Train] Step: 77500, loss: 0.00000, acc: 1.00000
[Train] Step: 78000, loss: 0.00000, acc: 1.00000
[Train] Step: 78500, loss: 0.00000, acc: 1.00000
[Train] Step: 79000, loss: 0.00000, acc: 1.00000
[Train] Step: 79500, loss: 0.00000, acc: 1.00000
[Train] Step: 80000, loss: 0.00000, acc: 1.00000
(1716, 307)
(1716,)
[Test ] Step: 80000, acc: 0.79143
[Train] Step: 80500, loss: 0.00000, acc: 1.00000
[Train] Step: 81000, loss: 0.00000, acc: 1.00000
[Train] Step: 81500, loss: 0.00000, acc: 1.00000
[Train] Step: 82000, loss: 0.00000, acc: 1.00000
[Train] Step: 82500, loss: 0.00000, acc: 1.00000
[Train] Step: 83000, loss: 0.00000, acc: 1.00000
[Train] Step: 83500, loss: 0.00000, acc: 1.00000
[Train] Step: 84000, loss: 0.00000, acc: 1.00000
[Train] Step: 84500, loss: 0.00000, acc: 1.00000
[Train] Step: 85000, loss: 0.00000, acc: 1.00000
(1716, 307)
(1716,)
[Test ] Step: 85000, acc: 0.79000
[Train] St

KeyboardInterrupt: 